### PR TITLE
fix(docs): add full examples for compress tasks

### LINKED ISSUE #61: ArchiveCompress task unable to read from Kestra's internal storage
### Expected Behavior

ArchiveCompress task should be able to archive compress a file from Kestra's internal storage.

### Actual Behaviour

On providing the file from Kestra's internal storage, the job errors out with the following error:

```
2024-02-17 17:00:57.285 Unrecognized token 'kestra': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"kestra:///company/team/compression-1/executions/1lwBXDGJKAY9BVoBZD1wOh/tasks/httpdownload/43tZi7k6UHxj5Z9oxUz49L/17747190915210794141.csv"; line: 1, column: 7]
2024-02-17 17:00:57.285 com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'kestra': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"kestra:///company/team/compression-1/executions/1lwBXDGJKAY9BVoBZD1wOh/tasks/httpdownload/43tZi7k6UHxj5Z9oxUz49L/17747190915210794141.csv"; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:760)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3041)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2082)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:808)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4912)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3755)
	at io.kestra.plugin.compress.ArchiveCompress.writeArchive(ArchiveCompress.java:91)
	at io.kestra.plugin.compress.ArchiveCompress.run(ArchiveCompress.java:74)
	at io.kestra.plugin.compress.ArchiveCompress.run(ArchiveCompress.java:27)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:729)
```

### Steps To Reproduce

1. Use the following flow:

```
id: compression-1
namespace: company.team
tasks:
  - id: httpdownload
    type: io.kestra.plugin.fs.http.Download
    uri: "https://raw.githubusercontent.com/kestra-io/datasets/main/csv/products.csv"
  - id: archive_compress
    type: "io.kestra.plugin.compress.ArchiveCompress"
    from: "{{ outputs.httpdownload.uri }}"
    algorithm: ZIP
    compression: GZIP
```

2. Execute the flow.

### Environment Information

- Kestra Version: 0.14.4
- Plugin version: 0.14.4
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```
id: compression-1
namespace: company.team
tasks:
  - id: httpdownload
    type: io.kestra.plugin.fs.http.Download
    uri: "https://raw.githubusercontent.com/kestra-io/datasets/main/csv/products.csv"
  - id: archive_compress
    type: "io.kestra.plugin.compress.ArchiveCompress"
    from: "{{ outputs.httpdownload.uri }}"
    algorithm: ZIP
    compression: GZIP
```

### PR DESCRIPTION
**Pull request by shrutimantri**
Closes #61

### CODE REVIEW

File: src/main/java/io/kestra/plugin/compress/ArchiveDecompress.java [hunk 1]
```diff
@@ -36,11 +36,22 @@
...
-                "algorithm: ZIP",
-                "compression: GZIP"
-            }
+            full = true,
+            code = """
+                id: archive_decompress
+                namespace: company.team
+
+                inputs:
+                  - id: file      #compressed file
```
Comment (wrussell1999) [inline src/main/java/io/kestra/plugin/compress/ArchiveDecompress.java:45]: Can you add the comment as the input description instead? Think that will be clearer to the user and also reminds them that descriptions are a feature

File: src/main/java/io/kestra/plugin/compress/FileCompress.java [hunk 2]
```diff
@@ -28,10 +28,21 @@
...
-                "from: \"{{ inputs.files }}\"",
-                "compression: Z"
-            }
+            full = true,
+            code = """
+                id: file_compress
+                namespace: company.team
+                
+                inputs:
+                  - id: file  #file to be compressed
```
Comment (wrussell1999) [inline src/main/java/io/kestra/plugin/compress/FileCompress.java:37]: Same here - descriptions

File: src/main/java/io/kestra/plugin/compress/FileDecompress.java [hunk 3]
```diff
@@ -27,10 +27,21 @@
...
-                "from: \"{{ inputs.files }}\"",
-                "compression: Z"
-            }
+            full = true,
+            code = """
+                id: file_decompress
+                namespace: company.team
+                
+                inputs:
+                  - id: file  #file to be decompressed
```
Comment (wrussell1999) [inline src/main/java/io/kestra/plugin/compress/FileDecompress.java:36]: Descriptions

**Review by wrussell1999 — APPROVED** [review]
